---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "piper-tts.fullname" . }}
  labels:
    {{- include "piper-tts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "piper-tts.selectorLabels" . | nindent 6 }}
      type: piper-tts
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "piper-tts.labels" . | nindent 8 }}
        type: piper-tts
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "piper-tts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: "{{ coalesce $.Values.global.image.registry .registry }}/{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ coalesce $.Values.global.image.pullPolicy .pullPolicy }}
          {{- end }}
          args: 
            - --voice
            - nl_NL-mls_5809-medium
            - --max-piper-procs
            - "6"
            - --update-voices
          env:
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - name: piper
              containerPort: 10200
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "piper-tts.fullname" . }}-data-pvc
              mountPath: /data
      volumes:
        - name: {{ include "piper-tts.fullname" . }}-data-pvc
          persistentVolumeClaim:
            claimName: {{ template "piper-tts.fullname" . }}-data-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
