---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whisper-stt.fullname" . }}
  labels:
    {{- include "whisper-stt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "whisper-stt.selectorLabels" . | nindent 6 }}
      type: whisper-stt
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "whisper-stt.labels" . | nindent 8 }}
        type: whisper-stt
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "whisper-stt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: "{{ coalesce $.Values.global.image.registry .registry }}/{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ coalesce $.Values.global.image.pullPolicy .pullPolicy }}
          {{- end }}
          args:
            - --model
            - tiny-int8
            - --language
            - nl
            - --beam-size
            - "7"
            - --data-dir
            - "/data"
          env:
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - name: whisper
              containerPort: 10300
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "whisper-stt.fullname" . }}-data-pvc
              mountPath: /data
      volumes:
        - name: {{ include "whisper-stt.fullname" . }}-data-pvc
          persistentVolumeClaim:
            claimName: {{ template "whisper-stt.fullname" . }}-data-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
