apiVersion: v1
kind: Service
metadata:
  name: {{ include "whisper-stt.fullname" . }}
  labels:
    {{- include "whisper-stt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "whisper-stt.selectorLabels" . | nindent 4 }}
    type: whisper-stt
  ports:
    - name: whisper
      port: {{ .Values.service.port.whisper }}
      protocol: TCP
      targetPort: whisper
    
