---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wyoming-speech-to-phrase.fullname" . }}
  labels:
    {{- include "wyoming-speech-to-phrase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wyoming-speech-to-phrase.selectorLabels" . | nindent 6 }}
      type: wyoming-speech-to-phrase
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wyoming-speech-to-phrase.labels" . | nindent 8 }}
        type: wyoming-speech-to-phrase
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wyoming-speech-to-phrase.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: "{{ coalesce $.Values.global.image.registry .registry }}/{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ coalesce $.Values.global.image.pullPolicy .pullPolicy }}
          {{- end }}
          args: 
            - --hass-token
            - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzZTE5NDliMDBjNjQ0MWViOTRiNzY4NzJmNzZkM2IzYSIsImlhdCI6MTc2Nzk1OTkxOCwiZXhwIjoyMDgzMzE5OTE4fQ.AyljTCflsZC_7UMP7zX_4f3BaNqThWnOr2onHbA7kko
            - --hass-websocket-uri
            - ws://ha-home-assistant:8123/api/websocket
            - --train-dir
            - /train
            - --model-dir 
            - /models
            - --retrain-on-start
          ports:
            - name: wyoming
              containerPort: 10300
              protocol: TCP
            - name: https
              containerPort: 8099
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "wyoming-speech-to-phrase.fullname" . }}-models-pvc
              mountPath: /models
            - name: {{ include "wyoming-speech-to-phrase.fullname" . }}-train-pvc
              mountPath: /train
      volumes:
        - name: {{ include "wyoming-speech-to-phrase.fullname" . }}-models-pvc
          persistentVolumeClaim:
            claimName: {{ template "wyoming-speech-to-phrase.fullname" . }}-models-pvc
        - name: {{ include "wyoming-speech-to-phrase.fullname" . }}-train-pvc
          persistentVolumeClaim:
            claimName: {{ template "wyoming-speech-to-phrase.fullname" . }}-train-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
