apiVersion: v1
kind: Service
metadata:
  name: {{ include "wyoming-speech-to-phrase.fullname" . }}
  labels:
    {{- include "wyoming-speech-to-phrase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "wyoming-speech-to-phrase.selectorLabels" . | nindent 4 }}
    type: wyoming-speech-to-phrase
  ports:
    - name: wyoming
      port: {{ .Values.service.port.wyoming }}
      protocol: TCP
      targetPort: wyoming
    
