ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
  hosts:
    - host: ha.dev.k8s-frambozen.nl
      paths:
        path: /
        pathType: ImplementationSpecific
  tls:
    - secretName: home-assistant-tls
      hosts:
        - ha.dev.k8s-frambozen.nl

configuration:
  user_tracking:
    - platform: google_maps
      username: "ralph.smeets@gmail.com"

persistence:
  enabled: true
  storageClass: "nfs-client"
  accessModes:
    - ReadWriteMany
  size: 10Gi

mosquitto:
  enabled: false

nats:
  enabled: true
  service:
    type: LoadBalancer

zigbee2mqtt:
  enabled: false

zwavejs2mqtt:
  enabled: false