apiVersion: v1
kind: Service
metadata:
  name: {{ include "matter-hub.fullname" . }}
  labels:
    {{- include "matter-hub.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "matter-hub.selectorLabels" . | nindent 4 }}
  ports:
    - name: udp-matter
      port: 5540
      protocol: UDP
      targetPort: udp-matter
    - name: mdns
      port: 5353
      protocol: UDP
      targetPort: mdns
    - name: tcp-matter
      port: 5540
      protocol: TCP
      targetPort: tcp-matter
---
piVersion: v1
kind: Service
metadata:
  name: {{ include "matter-hub.fullname" . }}
  labels:
    {{- include "matter-hub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "matter-hub.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
