apiVersion: v1
kind: Service
metadata:
  name: {{ include "matter-hub.fullname" . }}-http
  labels:
    {{- include "matter-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "matter-hub.selectorLabels" . | nindent 4 }}
    type: http
  ports:
    - name: http
      port: {{ .Values.service.port.http }}
      protocol: TCP
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matter-hub.fullname" . }}-matter
  labels:
    {{- include "matter-hub.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "matter-hub.selectorLabels" . | nindent 4 }}
    type: matter
  ports:
    - name: matter
      port: {{ .Values.service.port.matter }}
      protocol: TCP
      targetPort: matter
   