{{- if .Values.openhasp.enabled -}}
{{- range $path, $_ := .Files.Glob "**/plate.jsonl" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhasp-{{ . }}
data:
{{ (.Files.Glob "$path/*").AsConfig | indent 2 }}
{{- end -}}
{{- end -}}