{{- if .Values.openhasp.enabled -}}
{{- range .Values.openhasp.plates }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhasp-{{ . }}
data:
  {{ .name }}.yaml: |-
{{ .Values.openhasp.definitions | indent 4 }}
{{- end -}}
{{- end -}}