{{- if .Values.openhasp.enabled -}}
{{- range $name, $val := .Values.openhasp.plates }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhasp-{{ $name }}
data:
  {{ .name }}: |-
{{ get .Values.openhasp.definitions ( get $val "config" ) | indent 4 }}
{{- end -}}
{{- end -}}