{{- if .Values.openhasp.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhasp-{{ $name }}
data:
{{- range $name, $val := .Values.openhasp.configs }}
  {{ $name }}: {{ $val }}
{{- end -}}
{{- end -}}